{{- $fullName := include "nextjs-app.fullname" . -}}
{{- $defaultTarget := printf "%s-secret" $fullName -}}
{{- range $name, $config := .Values.externalSecrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $config.name | default ( printf "%s-secret" $fullName ) }}
  namespace: {{ $.Release.Namespace }}
spec:
  secretStoreRef:
    name: {{ $config.secretStore | default $.Values.defaultSecretStore }}
    kind: {{ $config.secretStoreKind | default $.Values.defaultSecretStoreKind | default "ClusterSecretStore" }}
  refreshInterval: {{ $config.refreshInterval | default $.Values.defaultRefreshInterval | default "10m" }}
  target:
    name: {{ $config.target | default $defaultTarget }}
    creationPolicy: {{ $config.creationPolicy | default $.Values.defaultCreationPolicy | default "Owner" }}
  {{- if $config.optional }}
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Fake
          name: fake-generator
  {{- end }}
  {{- if hasKey $config "data" }}
  data:
    {{- range $item := $config.data }}
    - secretKey: {{ $item.secretKey }}
      remoteRef:
        key: {{ $item.remoteRef.key }}
        {{- if hasKey $item.remoteRef "property" }}
        property: {{ $item.remoteRef.property }}
        {{- end }}
        {{- if hasKey $item.remoteRef "version" }}
        version: {{ $item.remoteRef.version | quote }}
        {{- end }}
    {{- end }}
  {{- else }}
  data:
  {{- if hasKey $config "secrets" }}
    {{- range $secret := $config.secrets }}
      {{- if hasKey $secret "properties" }}
        {{- range $secret.properties }}
    - secretKey: {{ . }}
      remoteRef:
        key: {{ $secret.remoteRef.key }}
        property: {{ . }}
          {{- if hasKey $secret.remoteRef "version" }}
        version: {{ $secret.remoteRef.version | quote }}
          {{- end }}
        {{- end }}
      {{- else if hasKey $secret "remoteRef" }}
    - secretKey: {{ base $secret.remoteRef.key | replace "." "_" }}
      remoteRef:
        key: {{ $secret.remoteRef.key }}
        {{- if hasKey $secret.remoteRef "version" }}
        version: {{ $secret.remoteRef.version | quote }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- else if hasKey $config "properties" }}
    {{- if hasKey $config "remoteRef" }}
      {{- range $config.properties }}
    - secretKey: {{ . }}
      remoteRef:
        key: {{ $config.remoteRef.key }}
        property: {{ . }}
        {{- if hasKey $config.remoteRef "version" }}
        version: {{ $config.remoteRef.version | quote }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- else if hasKey $config "dataFrom" }}
    {{- toYaml $config.dataFrom | nindent 2 }}
  {{- else if hasKey $config "remoteRef" }}
    - secretKey: {{ base $config.remoteRef.key | replace "." "_" }}
      remoteRef:
        key: {{ $config.remoteRef.key }}
        {{- if hasKey $config.remoteRef "version" }}
        version: {{ $config.remoteRef.version | quote }}
        {{- end }}
  {{- end }}
  {{- end }}
  {{- if hasKey $config "transform" }}
  template:
    {{- range $transform := $config.transform }}
    {{ $transform.secretKey }}: |
      {{ $transform.template }}
    {{- end }}
  {{- end }}
---
{{- end }}
